name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - v2  # Change this to match the branch you're pushing to

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
            # Set the API_KEY as an environment variable for the build process
      - name: Set API_KEY environment variable
        run: echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> $GITHUB_ENV
      - name: Build and export
        run: npm run build && npm run export
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist  # Change this if you're using a different folder for exports
